cabal-version: 3.4
name: reactive-home
version: 0.1.0.0
description: Please see the README on GitHub at <https://github.com/konn/reactive-home#readme>
homepage: https://github.com/konn/reactive-home#readme
bug-reports: https://github.com/konn/reactive-home/issues
author: Hiromi ISHII
maintainer: konn.jinro_at_gmail.com
copyright: (c) Hiromi ISHII 2026- present
license: BSD-3-Clause
license-file: LICENSE
build-type: Simple
tested-with:
  ghc ==9.12.4

data-dir: data
extra-doc-files:
  CHANGELOG.md
  README.md

source-repository head
  type: git
  location: https://github.com/konn/reactive-home
  subdir: reactive-home

common defaults
  other-modules: Paths_reactive_home
  autogen-modules: Paths_reactive_home
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints
    -Wunused-packages

  build-depends: base >=4.7 && <5
  default-language: GHC2021
  default-extensions:
    BlockArguments
    DataKinds
    FlexibleContexts
    FlexibleInstances
    GeneralizedNewtypeDeriving
    MultiParamTypeClasses
    RankNTypes
    TypeFamilies
    TypeOperators

library
  import: defaults
  hs-source-dirs: src
  -- cabal-gild: discover src --exclude=src/**/Internal.hs --exclude=src/**/Internal/**/*.hs
  exposed-modules:
    Home.Reactive
    Home.Reactive.App
    Home.Reactive.App.Types
    Home.Reactive.ESPresense
    Home.Reactive.MQTT
    Home.Reactive.Metrics.Mackerel
    Home.Reactive.Orphans
    Home.Reactive.Sesame5
    Home.Reactive.Utils

  -- cabal-gild: discover src --include=src/**/Internal.hs --include=src/**/Internal/**/*.hs
  other-modules:
  build-depends:
    aeson,
    bytestring,
    containers,
    dlist,
    effectful,
    generic-lens,
    hashable,
    hasquitto-auto-reconnect,
    hasquitto-core,
    hasquitto-effectful,
    lens,
    monad-schedule,
    monoidal-containers,
    optparse-applicative,
    rhine,
    safe-exceptions,
    stm-containers,
    text,
    time,
    tomland,
    transformers,
    unordered-containers,
    validation-selective,
    wreq-effectful,

executable reactive-home
  import: defaults
  hs-source-dirs: app
  main-is: Main.hs
  -- cabal-gild: discover app --exclude=app/Main.hs
  other-modules:
  ghc-options:
    -threaded
    -rtsopts
    "-with-rtsopts=-N --copying-gc"

  build-depends:
    reactive-home

test-suite reactive-home-test
  import: defaults
  type: exitcode-stdio-1.0
  main-is: Test.hs
  hs-source-dirs: test
  -- cabal-gild: discover test --exclude=test/Test.hs
  other-modules:
    Home.Reactive.AppTest
    Home.Reactive.ESPresenseTest

  build-tool-depends:
    tasty-discover:tasty-discover

  ghc-options:
    -threaded
    -O2
    -rtsopts
    -with-rtsopts=-N

  build-depends:
    reactive-home,
    tasty,
    tasty-hunit,
    text,
    tomland,
    unordered-containers,
