cabal-version: 3.4
name: haskesame-mqtt
version: 0.1.0.0
description: Please see the README on GitHub at <https://github.com/konn/reactive-home/haskesame-mqtt#readme>
homepage: https://github.com/konn/reactive-home#readme
bug-reports: https://github.com/konn/reactive-home/issues
author: Hiromi ISHII
maintainer: konn.jinro_at_gmail.com
copyright: (c) Hiromi ISHII 2026- present
license: BSD-3-Clause
license-file: LICENSE
build-type: Simple
tested-with:
  ghc ==9.12.4

extra-doc-files:
  CHANGELOG.md
  README.md

source-repository head
  type: git
  location: https://github.com/konn/reactive-home
  subdir: haskesame-mqtt

common defaults
  autogen-modules: Paths_haskesame_mqtt
  other-modules: Paths_haskesame_mqtt
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints
    -Wunused-packages

  default-language: GHC2021
  default-extensions:
    BlockArguments
    DerivingStrategies
    DuplicateRecordFields
    LambdaCase
    NoFieldSelectors
    OverloadedRecordDot
    OverloadedStrings
    PatternSynonyms
    RecordWildCards
    ScopedTypeVariables
    TypeApplications

  build-depends: base >=4.7 && <5

library
  import: defaults
  hs-source-dirs: src
  -- cabal-gild: discover src --exclude=src/**/Internal.hs --exclude=src/**/Internal/**/*.hs
  exposed-modules:
    Network.Sesame.Mqtt
    Network.Sesame.Mqtt.Bridge
    Network.Sesame.Mqtt.Types

  -- cabal-gild: discover src --include=src/**/Internal.hs --include=src/**/Internal/**/*.hs
  other-modules:
  build-depends:
    aeson,
    async,
    bytestring,
    containers,
    haskesame-core,
    hasquitto-auto-reconnect,
    random,
    safe-exceptions,
    stm,
    stm-containers,
    text,
    time,
    uuid,

test-suite haskesame-mqtt-test
  import: defaults
  type: exitcode-stdio-1.0
  main-is: Test.hs
  hs-source-dirs: test
  -- cabal-gild: discover test --exclude=test/Test.hs
  other-modules:
  ghc-options:
    -threaded
    -O2
    -rtsopts
    -with-rtsopts=-N
